/**
 * Walkthrough Val — Hono HTTP handler.
 *
 * Serves walkthrough HTML out of Val Town blob storage and
 * manages comments via SQLite, with email magic-code auth for
 * writes. Reads are open (unauthenticated visitors can see
 * discussions); writes require an authenticated session token.
 *
 * At-rest encryption posture (see docs/encryption.md):
 *
 * - Comment body + author: envelope-encrypted (per-row DEK wrapped under a
 *   database wrapping key). Rotation means re-wrap each row's small DEK; bodies
 *   are never decrypted.
 * - Walkthrough HTML: opt-in. The publisher passes `encryptBlobs: true` in
 *   meander.config.json and uploads ENVELOPE-prefixed blobs; the val recognizes
 *   the prefix and decrypts using `MEANDER_BLOB_KEY`. Plaintext blobs (no
 *   prefix) are served as-is. Most projects publish to GitHub Pages and don't
 *   engage this path at all.
 *
 * Required env vars (set by ops via `meander db key init`):
 * MEANDER_DB_KEY_<n>             Hex-encoded 32-byte wrapping
 * key for generation N (one var per
 * generation). New comments wrap
 * their DEK under the *current*
 * generation; old generations stay
 * live as long as any row still
 * references them.
 * MEANDER_DB_KEY_CURRENT         Integer pointer — which
 * generation new writes use.
 * MEANDER_JWT_SECRET             Random secret used to sign session JWTs.
 * Generated by deploy-val once;
 * rotating invalidates every active
 * login session.
 *
 * Optional env vars:
 * MEANDER_BLOB_KEY               Hex-encoded 32-byte wrapping key
 * for envelope-encrypted blobs. Set
 * by ops via `meander blob key init`
 * when `encryptBlobs: true`.
 * MEANDER_ALLOWED_EMAIL_DOMAINS  Comma-separated allowlist, e.g.
 * "gmail.com,socket.dev". Empty / unset
 * means writes are refused — the safe
 * default for a fresh deploy.
 * MEANDER_OUT_DIR                Blob-key prefix (default: "pages").
 * Must match what publish emits.
 * MEANDER_DEMO_MODE              When "true", composer is still
 * enabled but comments return a 403 at
 * write time. UI shows a banner.
 *
 * Blob key conventions:
 * <outDir>/<slug>/index.html           plaintext or ENVELOPE-prefixed
 * <outDir>/<slug>/part-<N>.html        plaintext or ENVELOPE-prefixed
 * <outDir>/<slug>/documents.html       plaintext or ENVELOPE-prefixed
 * <outDir>/<slug>/manifest.json        plaintext
 * <outDir>/meander.css                 plaintext.
 */

import { blob } from 'https://esm.town/v/std/blob'
import { sqlite } from 'https://esm.town/v/std/sqlite/main.ts'
import { Hono } from 'npm:hono@4'
import type { Context } from 'npm:hono@4'
import {
  emailDomainAllowed,
  hashCode,
  parseAllowedDomains,
  sixDigitCode,
} from './lib/auth.ts'
import { registerAdminRoutes } from './lib/admin.ts'
import { registerCommentRoutes } from './lib/comments.ts'
import { decrypt, importKey, unpackEnvelope, unwrapKey } from './lib/crypto.ts'
import { signJwt, verifyJwt } from './lib/jwt.ts'
import { loadBlobKey, loadDbKeyContext } from './lib/keys.ts'
import type { WrappingKeyContext } from './lib/keys.ts'
import { errorMessage } from '@socketsecurity/lib/errors/message'
import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'

const logger = getDefaultLogger()

const app = new Hono()

/* ------------------------------------------------------------------ */
/*  Config                                                              */
/* ------------------------------------------------------------------ */

const OUT_DIR = (Deno.env.get('MEANDER_OUT_DIR') || 'pages').replace(/\/$/, '')
const JWT_SECRET = Deno.env.get('MEANDER_JWT_SECRET') || ''
const ADMIN_TOKEN = Deno.env.get('MEANDER_ADMIN_TOKEN') || ''
const ALLOWED_EMAIL_DOMAINS = parseAllowedDomains(
  Deno.env.get('MEANDER_ALLOWED_EMAIL_DOMAINS'),
)
const DEMO_MODE = Deno.env.get('MEANDER_DEMO_MODE') === 'true'

/* ------------------------------------------------------------------ */
/*  Module state                                                        */
/* ------------------------------------------------------------------ */

/* Module-load: if MEANDER_DB_KEY_<n> is set but MEANDER_DB_KEY_CURRENT
 * is missing or malformed, loadDbKeyContext throws. Catch it and
 * keep the val process alive — we'd rather fail per-request with a
 * descriptive 500 than 502 every reader because of a bad pointer.
 * The error message becomes the body for any /api/comments/* call. */
let dbKeyContext: WrappingKeyContext | undefined
let dbKeyContextError: string | undefined
try {
  dbKeyContext = loadDbKeyContext()
} catch (e) {
  dbKeyContextError = errorMessage(e)
}

let dbInitialized = false

/* ------------------------------------------------------------------ */
/*  Handlers + helpers (sorted alphanumerically)                        */
/* ------------------------------------------------------------------ */

export function authRequired(
  email: string | undefined,
): { error: string; status: 401 | 403 } | undefined {
  if (DEMO_MODE) {
    return { error: 'demo mode — writes disabled', status: 403 }
  }
  if (!email) {
    return { error: 'authentication required', status: 401 }
  }
  if (ALLOWED_EMAIL_DOMAINS.length === 0) {
    return {
      error: 'writes disabled — server has no MEANDER_ALLOWED_EMAIL_DOMAINS',
      status: 403,
    }
  }
  if (!emailDomainAllowed(email, ALLOWED_EMAIL_DOMAINS)) {
    return { error: 'email domain not allowed', status: 403 }
  }
  return undefined
}

/**
 * Read the bearer token from `Authorization: Bearer <jwt>` and
 * verify it. Returns the email, or undefined (no token / bad token).
 */
export async function currentUser(c: Context): Promise<string | undefined> {
  if (!JWT_SECRET) {
    return undefined
  }
  const auth = c.req.header('authorization') || ''
  const m = auth.match(/^Bearer\s+(.+)$/i)
  if (!m) {
    return undefined
  }
  return readSession(m[1]!)
}

export async function ensureDb() {
  if (dbInitialized) {
    return
  }
  await sqlite.execute(`
    CREATE TABLE IF NOT EXISTS comments (
      id              TEXT PRIMARY KEY,
      slug            TEXT NOT NULL,
      part            INTEGER NOT NULL,
      file            TEXT NOT NULL,
      line_from       INTEGER NOT NULL,
      line_to         INTEGER NOT NULL,
      author          TEXT NOT NULL,
      body            TEXT NOT NULL,
      dek_wrapped     TEXT NOT NULL,
      key_generation  INTEGER NOT NULL,
      parent_id       TEXT,
      resolved        INTEGER NOT NULL DEFAULT 0,
      created_at      TEXT NOT NULL DEFAULT (datetime('now'))
    )
  `)
  await sqlite.execute(
    `CREATE INDEX IF NOT EXISTS idx_comments_slug_part ON comments(slug, part)`,
  )
  await sqlite.execute(
    `CREATE INDEX IF NOT EXISTS idx_comments_key_generation ON comments(key_generation)`,
  )
  await sqlite.execute(`
    CREATE TABLE IF NOT EXISTS magic_codes (
      email      TEXT PRIMARY KEY,
      code_hash  TEXT NOT NULL,
      expires_at INTEGER NOT NULL,
      attempts   INTEGER NOT NULL DEFAULT 0
    )
  `)
  dbInitialized = true
}

/**
 * Mint a 30-day session JWT with the caller's email.
 */
export async function mintSession(email: string): Promise<string> {
  const now = Math.floor(Date.now() / 1000)
  return signJwt({ email, iat: now, exp: now + 60 * 60 * 24 * 30 }, JWT_SECRET)
}

/**
 * Verify a token and return the email claim, or undefined.
 */
export async function readSession(token: string): Promise<string | undefined> {
  const payload = await verifyJwt(token, JWT_SECRET)
  if (!payload || typeof payload['email'] !== 'string') {
    return undefined
  }
  return payload['email']
}

/**
 * Send the magic code via Val Town's std/email. Falls back to
 * logging the code to stdout when the provider call fails (dev
 * deploys, offline testing) so setup isn't blocked.
 */
export async function sendMagicCode(
  email: string,
  code: string,
): Promise<void> {
  const subject = 'Your meander sign-in code'
  const text = `Your sign-in code is: ${code}\n\nIt expires in 10 minutes.\n`
  try {
    // oxlint-disable-next-line socket/no-dynamic-import-outside-bundle -- lazy-load val-town std/email only on the write/auth path so read requests never import it; the surrounding try/catch keeps module load resilient when the email module is unavailable.
    const { email: sendEmail } = await import('https://esm.town/v/std/email')
    await sendEmail({ to: email, subject, text })
  } catch (e) {
    logger.log(`[meander] email send failed, code for ${email}: ${code}`, e)
  }
}

/**
 * Serve a walkthrough HTML blob. If the publisher uploaded an
 * envelope-encrypted blob (recognized by the `ENVELOPE:` prefix),
 * decrypt before serving. Plaintext blobs pass through. Failure
 * to decrypt — wrong key, malformed envelope — surfaces as a 500
 * so misconfiguration doesn't silently serve garbage.
 */
export async function serveBlobHtml(c: Context, relativeKey: string) {
  let text: string
  try {
    const data = await blob.get(`${OUT_DIR}/${relativeKey}`)
    text = await data.text()
  } catch {
    return c.text('Not found', 404)
  }
  let envelope: { wrappedDek: string; ciphertext: string } | undefined
  try {
    envelope = unpackEnvelope(text)
  } catch {
    return c.text('Server error: malformed encrypted blob', 500)
  }
  if (!envelope) {
    return c.html(text)
  }
  const blobKey = await loadBlobKey()
  if (!blobKey) {
    return c.text(
      'Server error: encrypted blob present but MEANDER_BLOB_KEY is unset',
      500,
    )
  }
  try {
    const dekBytes = await unwrapKey(envelope.wrappedDek, blobKey)
    const dek = await importKey(dekBytes)
    const html = await decrypt(envelope.ciphertext, dek)
    return c.html(html)
  } catch {
    return c.text('Server error: blob decrypt failed', 500)
  }
}

export async function serveBlobText(
  c: Context,
  key: string,
  contentType: string,
) {
  try {
    const data = await blob.get(`${OUT_DIR}/${key}`)
    const text = await data.text()
    return c.text(text, 200, {
      'Content-Type': `${contentType}; charset=utf-8`,
    })
  } catch {
    return c.text('Not found', 404)
  }
}

/* ------------------------------------------------------------------ */
/*  Auth routes                                                         */
/* ------------------------------------------------------------------ */

/**
 * POST /api/auth/request  { email }
 * Mints a 6-digit code, stores the hash, sends it via email.
 */
app.post('/api/auth/request', async c => {
  await ensureDb()
  const body = await c.req.json().catch(() => ({}))
  const email = typeof body?.email === 'string' ? body.email.trim() : ''
  if (!email || email.indexOf('@') < 0) {
    return c.json({ error: 'email required' }, 400)
  }
  if (ALLOWED_EMAIL_DOMAINS.length === 0) {
    return c.json(
      {
        error:
          'writes disabled — server has no MEANDER_ALLOWED_EMAIL_DOMAINS configured',
      },
      403,
    )
  }
  if (!emailDomainAllowed(email, ALLOWED_EMAIL_DOMAINS)) {
    return c.json({ error: 'email domain not allowed' }, 403)
  }
  const code = sixDigitCode()
  const codeHash = await hashCode(code, email)
  const expiresAt = Math.floor(Date.now() / 1000) + 10 * 60
  await sqlite.execute({
    sql: `
      INSERT INTO magic_codes (email, code_hash, expires_at, attempts)
      VALUES (:email, :codeHash, :expiresAt, 0)
      ON CONFLICT(email) DO UPDATE SET
        code_hash = excluded.code_hash,
        expires_at = excluded.expires_at,
        attempts = 0
    `,
    args: { email, codeHash, expiresAt },
  })
  await sendMagicCode(email, code)
  return c.json({ ok: true })
})

/**
 * POST /api/auth/verify  { email, code }
 * Returns { token } on success. Token goes in Authorization:
 * Bearer for subsequent write calls.
 */
app.post('/api/auth/verify', async c => {
  await ensureDb()
  if (!JWT_SECRET) {
    return c.json({ error: 'server missing MEANDER_JWT_SECRET' }, 500)
  }
  const body = await c.req.json().catch(() => ({}))
  const email = typeof body?.email === 'string' ? body.email.trim() : ''
  const code = typeof body?.code === 'string' ? body.code.trim() : ''
  if (!email || !code) {
    return c.json({ error: 'email + code required' }, 400)
  }
  const row = (
    await sqlite.execute({
      sql: 'SELECT code_hash, expires_at, attempts FROM magic_codes WHERE email = :email',
      args: { email },
    })
  ).rows[0] as
    | { code_hash: string; expires_at: number; attempts: number }
    | undefined
  if (!row) {
    return c.json({ error: 'no code for this email' }, 400)
  }
  if (row.expires_at < Math.floor(Date.now() / 1000)) {
    return c.json({ error: 'code expired' }, 400)
  }
  if (row.attempts >= 5) {
    return c.json({ error: 'too many attempts; request a new code' }, 429)
  }
  const codeHash = await hashCode(code, email)
  if (codeHash !== row.code_hash) {
    await sqlite.execute({
      sql: 'UPDATE magic_codes SET attempts = attempts + 1 WHERE email = :email',
      args: { email },
    })
    return c.json({ error: 'invalid code' }, 401)
  }
  /* One-shot: delete the code after successful use. */
  await sqlite.execute({
    sql: 'DELETE FROM magic_codes WHERE email = :email',
    args: { email },
  })
  const token = await mintSession(email)
  return c.json({ token, email })
})

/**
 * GET /api/auth/me — echoes the authenticated email, or 401.
 * Useful for the client to check session freshness on load.
 */
app.get('/api/auth/me', async c => {
  const email = await currentUser(c)
  if (!email) {
    return c.json({ error: 'not authenticated' }, 401)
  }
  return c.json({ email, demoMode: DEMO_MODE })
})

/* ------------------------------------------------------------------ */
/*  Shared CSS                                                          */
/* ------------------------------------------------------------------ */

app.get('/meander.css', async c => serveBlobText(c, 'meander.css', 'text/css'))

/* ------------------------------------------------------------------ */
/*  Root — list available walkthroughs                                 */
/* ------------------------------------------------------------------ */

app.get('/', async c => {
  try {
    const blobs = await blob.list(`${OUT_DIR}/`)
    const slugs = new Set<string>()
    for (const b of blobs) {
      /* Keys look like <OUT_DIR>/<slug>/index.html. The shared
       * CSS file lives at <OUT_DIR>/meander.css — its key has
       * only two segments, so the slug branch skips it. */
      const parts = b.key.split('/')
      if (parts.length >= 3 && parts[0] === OUT_DIR) {
        slugs.add(parts[1]!)
      }
    }
    const links = [...slugs]
      .map(s => `<li><a href="/${s}/">${s}</a></li>`)
      .join('\n')
    const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Walkthroughs</title>
<link rel="stylesheet" href="/meander.css"></head>
<body><header class="topbar"><h1>Walkthroughs</h1></header>
<main style="padding:16px;max-width:900px;"><ul>${links || '<li>No walkthroughs published yet.</li>'}</ul></main></body></html>`
    return c.html(html)
  } catch {
    return c.text('Error listing walkthroughs', 500)
  }
})

/* ------------------------------------------------------------------ */
/*  Walkthrough pages                                                   */
/* ------------------------------------------------------------------ */

app.get('/:slug/', async c => {
  const slug = c.req.param('slug')
  return serveBlobHtml(c, `${slug}/index.html`)
})

app.get('/:slug', async c => {
  const slug = c.req.param('slug')
  return c.redirect(`/${slug}/`, 301)
})

app.get('/:slug/documents', async c => {
  const slug = c.req.param('slug')
  return serveBlobHtml(c, `${slug}/documents.html`)
})

app.get('/:slug/part/:id', async c => {
  const slug = c.req.param('slug')
  const id = c.req.param('id')
  return serveBlobHtml(c, `${slug}/part-${id}.html`)
})

/* ------------------------------------------------------------------ */
/*  Comments + admin endpoints                                          */
/* ------------------------------------------------------------------ */

/* Routes are registered from `lib/comments.ts` and `lib/admin.ts`
 * so tests can drive them with a stub sqlite client + key context,
 * without pulling in val.town's `https://esm.town/...` imports at
 * test time. */
registerCommentRoutes(app, {
  sqlite,
  ensureDb,
  currentUser,
  authRequired,
  keyContext: dbKeyContext,
  keyContextError: dbKeyContextError,
})

registerAdminRoutes(app, {
  sqlite,
  ensureDb,
  keyContext: dbKeyContext,
  keyContextError: dbKeyContextError,
  adminToken: ADMIN_TOKEN,
})

/* ------------------------------------------------------------------ */
/*  Export                                                              */
/* ------------------------------------------------------------------ */

// oxlint-disable-next-line socket/no-default-export -- val-town runtime invokes the module's default export as the fetch handler.
export default app.fetch
