/**
 * Walkthrough Val — Hono HTTP handler.
 *
 * Serves walkthrough HTML out of Val Town blob storage and
 * manages comments via SQLite, with email magic-code auth. Comment
 * writes and the comment export require an authenticated session
 * token. Comment reads are open on a public walkthrough and carry
 * the same reader gate as the prose on a private one.
 *
 * At-rest encryption posture (see docs/encryption.md):
 *
 * - Comment body + author: envelope-encrypted (per-row DEK wrapped under a
 *   database wrapping key). Rotation means re-wrap each row's small DEK; bodies
 *   are never decrypted.
 * - Walkthrough HTML: opt-in. The publisher passes `encryptBlobs: true` in
 *   meander.config.json and uploads ENVELOPE-prefixed blobs; the val recognizes
 *   the prefix and decrypts using `MEANDER_BLOB_KEY`. Plaintext blobs (no
 *   prefix) are served as-is. Most projects publish to GitHub Pages and don't
 *   engage this path at all.
 *
 * `encryptBlobs` is both the at-rest control and the reader gate.
 * A walkthrough whose blob carries the `ENVELOPE:` prefix is
 * private: `lib/pages.ts` resolves the caller before decrypting,
 * and refuses with the sign-in page unless they present the slug's
 * reader cookie, a comment-API session token, or the val's admin
 * token. A plaintext blob stays public with no sign-in. The reader
 * cookie is minted by `POST /:slug/api/auth/session` and scoped to
 * `Path=/<slug>/`, which is how a top-level browser navigation
 * carries credentials the `Authorization` header cannot.
 *
 * The comment read routes accept the same three credentials on a
 * private walkthrough, because a comment thread carries decrypted
 * prose and author identities of its own. They decide from the
 * `walkthrough_visibility` table rather than the blob, so a comment
 * poll costs an indexed row read instead of a blob fetch; see
 * `lib/visibility.ts` for who writes that table and why an
 * unrecorded slug reads as private.
 *
 * Required env vars (set by ops via `meander db key init`):
 * MEANDER_DB_KEY_<n>             Hex-encoded 32-byte wrapping
 * key for generation N (one var per
 * generation). New comments wrap
 * their DEK under the *current*
 * generation; old generations stay
 * live as long as any row still
 * references them.
 * MEANDER_DB_KEY_CURRENT         Integer pointer — which
 * generation new writes use.
 * MEANDER_JWT_SECRET             Random secret used to sign session JWTs.
 * Generated by deploy-val once;
 * rotating invalidates every active
 * login session.
 *
 * Optional env vars:
 * MEANDER_BLOB_KEY               Hex-encoded 32-byte wrapping key
 * for envelope-encrypted blobs. Set
 * by ops via `meander blob key init`
 * when `encryptBlobs: true`.
 * MEANDER_ALLOWED_EMAIL_DOMAINS  Comma-separated allowlist, e.g.
 * "gmail.com,socket.dev". Empty / unset
 * means writes are refused — the safe
 * default for a fresh deploy.
 * MEANDER_OUT_DIR                Blob-key prefix (default: "pages").
 * Must match what publish emits.
 * MEANDER_DEMO_MODE              When "true", composer is still
 * enabled but comments return a 403 at
 * write time. UI shows a banner.
 *
 * Blob key conventions:
 * <outDir>/<slug>/index.html           plaintext or ENVELOPE-prefixed
 * <outDir>/<slug>/part-<N>.html        plaintext or ENVELOPE-prefixed
 * <outDir>/<slug>/documents.html       plaintext or ENVELOPE-prefixed
 * <outDir>/<slug>/manifest.json        plaintext
 * <outDir>/meander.css                 plaintext.
 */

import { blob } from 'https://esm.town/v/std/blob'
import { sqlite } from 'https://esm.town/v/std/sqlite/main.ts'
import { Hono } from 'npm:hono@4'
import type { Context } from 'npm:hono@4'
import {
  authGate,
  emailDomainAllowed,
  hashCode,
  parseAllowedDomains,
  sixDigitCode,
} from './lib/auth.ts'
import type { AuthGateOptions } from './lib/auth.ts'
import { registerAdminRoutes } from './lib/admin.ts'
import { registerCommentRoutes } from './lib/comments.ts'
import {
  consumeMagicCode,
  MAGIC_CODE_TTL_SECONDS,
  storeMagicCode,
} from './lib/magic-code.ts'
import { loadBlobKey, loadDbKeyContext } from './lib/keys.ts'
import type { WrappingKeyContext } from './lib/keys.ts'
import { registerPageRoutes } from './lib/pages.ts'
import { mintSessionToken, readSessionToken } from './lib/session.ts'
import {
  probeSlugPrivacy,
  resolveSlugPrivacy,
  WALKTHROUGH_VISIBILITY_TABLE_SQL,
} from './lib/visibility.ts'
import { errorMessage } from '@socketsecurity/lib/errors/message'
import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'

const logger = getDefaultLogger()

const app = new Hono()

/* ------------------------------------------------------------------ */
/*  Config                                                              */
/* ------------------------------------------------------------------ */

const OUT_DIR = (Deno.env.get('MEANDER_OUT_DIR') || 'pages').replace(/\/$/, '')
const JWT_SECRET = Deno.env.get('MEANDER_JWT_SECRET') || ''
const ADMIN_TOKEN = Deno.env.get('MEANDER_ADMIN_TOKEN') || ''
const ALLOWED_EMAIL_DOMAINS = parseAllowedDomains(
  Deno.env.get('MEANDER_ALLOWED_EMAIL_DOMAINS'),
)
const DEMO_MODE = Deno.env.get('MEANDER_DEMO_MODE') === 'true'

/* ------------------------------------------------------------------ */
/*  Module state                                                        */
/* ------------------------------------------------------------------ */

/* Module-load: if MEANDER_DB_KEY_<n> is set but MEANDER_DB_KEY_CURRENT
 * is missing or malformed, loadDbKeyContext throws. Catch it and
 * keep the val process alive — we'd rather fail per-request with a
 * descriptive 500 than 502 every reader because of a bad pointer.
 * The error message becomes the body for any /api/comments/* call.
 */
let dbKeyContext: WrappingKeyContext | undefined
let dbKeyContextError: string | undefined
try {
  dbKeyContext = loadDbKeyContext()
} catch (e) {
  dbKeyContextError = errorMessage(e)
}

let dbInitialized = false

/* ------------------------------------------------------------------ */
/*  Handlers + helpers (sorted alphanumerically)                        */
/* ------------------------------------------------------------------ */

/**
 * Bind `authGate` to this val's env config. The gate itself lives
 * in lib/auth.ts so Node tests can drive it without importing the
 * val-town modules this file loads at module scope.
 */
export function authRequired(
  email: string | undefined,
  options?: AuthGateOptions | undefined,
): { error: string; status: 401 | 403 } | undefined {
  const opts = { __proto__: null, ...options } as AuthGateOptions
  return authGate(email, {
    allowedDomains: ALLOWED_EMAIL_DOMAINS,
    demoMode: DEMO_MODE,
    operation: opts.operation,
  })
}

/**
 * Read the bearer token from `Authorization: Bearer <jwt>` and
 * verify it. Returns the email, or undefined (no token / bad token).
 */
export async function currentUser(c: Context): Promise<string | undefined> {
  if (!JWT_SECRET) {
    return undefined
  }
  const auth = c.req.header('authorization') || ''
  const m = auth.match(/^Bearer\s+(.+)$/i)
  if (!m) {
    return undefined
  }
  return readSession(m[1])
}

export async function ensureDb() {
  if (dbInitialized) {
    return
  }
  await sqlite.execute(`
    CREATE TABLE IF NOT EXISTS comments (
      id              TEXT PRIMARY KEY,
      slug            TEXT NOT NULL,
      part            INTEGER NOT NULL,
      file            TEXT NOT NULL,
      line_from       INTEGER NOT NULL,
      line_to         INTEGER NOT NULL,
      author          TEXT NOT NULL,
      body            TEXT NOT NULL,
      dek_wrapped     TEXT NOT NULL,
      key_generation  INTEGER NOT NULL,
      parent_id       TEXT,
      resolved        INTEGER NOT NULL DEFAULT 0,
      created_at      TEXT NOT NULL DEFAULT (datetime('now'))
    )
  `)
  await sqlite.execute(
    `CREATE INDEX IF NOT EXISTS idx_comments_slug_part ON comments(slug, part)`,
  )
  await sqlite.execute(
    `CREATE INDEX IF NOT EXISTS idx_comments_key_generation ON comments(key_generation)`,
  )
  await sqlite.execute(`
    CREATE TABLE IF NOT EXISTS magic_codes (
      email      TEXT PRIMARY KEY,
      code_hash  TEXT NOT NULL,
      expires_at INTEGER NOT NULL,
      attempts   INTEGER NOT NULL DEFAULT 0
    )
  `)
  /* `meander publish` creates this table too, with the identical
   * statement, because it records a slug's privacy before the val
   * has necessarily served its first request.
   */
  await sqlite.execute(WALKTHROUGH_VISIBILITY_TABLE_SQL)
  dbInitialized = true
}

/**
 * Is this walkthrough private? Reads the recorded flag, deriving
 * and persisting it from the blob store the first time a slug is
 * asked about. See lib/visibility.ts.
 */
export async function isSlugPrivate(slug: string): Promise<boolean> {
  await ensureDb()
  return resolveSlugPrivacy(sqlite, slug, s =>
    probeSlugPrivacy(readBlobText, s),
  )
}

/**
 * Every slug with blobs under the deployment's out-dir, sorted.
 */
export async function listSlugs(): Promise<string[]> {
  const blobs = await blob.list(`${OUT_DIR}/`)
  const slugs = new Set<string>()
  for (const b of blobs) {
    /* Keys look like <OUT_DIR>/<slug>/index.html. The shared
     * CSS file lives at <OUT_DIR>/meander.css — its key has
     * only two segments, so the slug branch skips it.
     */
    const parts = b.key.split('/')
    if (parts.length >= 3 && parts[0] === OUT_DIR) {
      slugs.add(parts[1])
    }
  }
  return [...slugs].toSorted()
}

/**
 * Mint a 30-day comment-API session token with the caller's email.
 */
export async function mintSession(email: string): Promise<string> {
  return mintSessionToken(email, JWT_SECRET)
}

/**
 * Blob text for a key relative to the out-dir, or undefined when
 * the blob does not exist.
 */
export async function readBlobText(
  relativeKey: string,
): Promise<string | undefined> {
  try {
    const data = await blob.get(`${OUT_DIR}/${relativeKey}`)
    return await data.text()
  } catch {
    return undefined
  }
}

/**
 * Verify a session token and return the email claim, or undefined.
 */
export async function readSession(token: string): Promise<string | undefined> {
  return readSessionToken(token, JWT_SECRET)
}

/**
 * Send the magic code via Val Town's std/email. Falls back to
 * logging the code to stdout when the provider call fails (dev
 * deploys, offline testing) so setup isn't blocked.
 */
export async function sendMagicCode(
  email: string,
  code: string,
): Promise<void> {
  const subject = 'Your meander sign-in code'
  const text = `Your sign-in code is: ${code}\n\nIt expires in 10 minutes.\n`
  try {
    // oxlint-disable-next-line socket/no-dynamic-import-outside-bundle -- lazy-load val-town std/email only on the write/auth path so read requests never import it; the surrounding try/catch keeps module load resilient when the email module is unavailable.
    const { email: sendEmail } = await import('https://esm.town/v/std/email')
    await sendEmail({ to: email, subject, text })
  } catch (e) {
    logger.log(`[meander] email send failed, code for ${email}: ${code}`, e)
  }
}

export async function serveBlobText(
  c: Context,
  key: string,
  contentType: string,
) {
  try {
    const data = await blob.get(`${OUT_DIR}/${key}`)
    const text = await data.text()
    return c.text(text, 200, {
      'Content-Type': `${contentType}; charset=utf-8`,
    })
  } catch {
    return c.text('Not found', 404)
  }
}

/* ------------------------------------------------------------------ */
/*  Auth routes                                                         */
/* ------------------------------------------------------------------ */

/**
 * POST /api/auth/request  { email }
 * Mints a 6-digit code, stores the hash, sends it via email.
 */
app.post('/api/auth/request', async c => {
  await ensureDb()
  const body = await c.req.json().catch(() => ({}))
  const email = typeof body?.email === 'string' ? body.email.trim() : ''
  if (!email || email.indexOf('@') < 0) {
    return c.json({ error: 'email required' }, 400)
  }
  if (ALLOWED_EMAIL_DOMAINS.length === 0) {
    return c.json(
      {
        error:
          'writes disabled — server has no MEANDER_ALLOWED_EMAIL_DOMAINS configured',
      },
      403,
    )
  }
  if (!emailDomainAllowed(email, ALLOWED_EMAIL_DOMAINS)) {
    return c.json({ error: 'email domain not allowed' }, 403)
  }
  const code = sixDigitCode()
  const codeHash = await hashCode(code, email)
  const expiresAt = Math.floor(Date.now() / 1000) + MAGIC_CODE_TTL_SECONDS
  await storeMagicCode(sqlite, email, codeHash, expiresAt)
  await sendMagicCode(email, code)
  return c.json({ ok: true })
})

/**
 * POST /api/auth/verify  { email, code }
 * Returns { token } on success. Token goes in Authorization:
 * Bearer for subsequent write calls.
 */
app.post('/api/auth/verify', async c => {
  await ensureDb()
  if (!JWT_SECRET) {
    return c.json({ error: 'server missing MEANDER_JWT_SECRET' }, 500)
  }
  const body = await c.req.json().catch(() => ({}))
  const email = typeof body?.email === 'string' ? body.email.trim() : ''
  const code = typeof body?.code === 'string' ? body.code.trim() : ''
  if (!email || !code) {
    return c.json({ error: 'email + code required' }, 400)
  }
  const outcome = await consumeMagicCode(sqlite, email, code)
  if (!outcome.ok) {
    return c.json({ error: outcome.error }, outcome.status)
  }
  const token = await mintSession(email)
  return c.json({ token, email })
})

/**
 * GET /api/auth/me — echoes the authenticated email, or 401.
 * Useful for the client to check session freshness on load.
 */
app.get('/api/auth/me', async c => {
  const email = await currentUser(c)
  if (!email) {
    return c.json({ error: 'not authenticated' }, 401)
  }
  return c.json({ email, demoMode: DEMO_MODE })
})

/* ------------------------------------------------------------------ */
/*  Shared CSS                                                          */
/* ------------------------------------------------------------------ */

app.get('/meander.css', async c => serveBlobText(c, 'meander.css', 'text/css'))

/* ------------------------------------------------------------------ */
/*  Walkthrough pages + comments + admin endpoints                      */
/* ------------------------------------------------------------------ */

/* Routes are registered from `lib/pages.ts`, `lib/comments.ts`, and
 * `lib/admin.ts` so tests can drive them with a stub blob store,
 * sqlite client, and key context, without pulling in val.town's
 * `https://esm.town/...` imports at test time.
 */
registerPageRoutes(app, {
  adminToken: ADMIN_TOKEN,
  allowedDomains: ALLOWED_EMAIL_DOMAINS,
  blobKey: loadBlobKey,
  consumeMagicCode: async (email, code) => {
    await ensureDb()
    return consumeMagicCode(sqlite, email, code)
  },
  jwtSecret: JWT_SECRET,
  listSlugs,
  readBlobText,
})

registerCommentRoutes(app, {
  sqlite,
  ensureDb,
  allowedDomains: ALLOWED_EMAIL_DOMAINS,
  currentUser,
  authRequired,
  isSlugPrivate,
  jwtSecret: JWT_SECRET,
  keyContext: dbKeyContext,
  keyContextError: dbKeyContextError,
  adminToken: ADMIN_TOKEN,
})

registerAdminRoutes(app, {
  sqlite,
  ensureDb,
  keyContext: dbKeyContext,
  keyContextError: dbKeyContextError,
  adminToken: ADMIN_TOKEN,
})

/* ------------------------------------------------------------------ */
/*  Export                                                              */
/* ------------------------------------------------------------------ */

// The val-town runtime invokes the module's default export as the fetch
// handler.
// oxlint-disable-next-line socket/no-default-export -- val-town entry
export default app.fetch
